#################################################################################
  #  Copyright (c) 2025 Cofinity-X
  #  Copyright (c) 2025 Contributors to the Eclipse Foundation
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0.
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #################################################################################


---

# this configmap contains all application configuration that is required by the issuerservice runtime.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "issuerservice-config"
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "issuerservice.labels" . | nindent 4 }}
data:

  #######
  # API #
  #######

  web.http.port: {{ .Values.issuerservice.endpoints.default.port | quote }}
  web.http.path: {{ .Values.issuerservice.endpoints.default.path | quote }}
  web.http.version.port: {{ .Values.issuerservice.endpoints.version.port | quote}}
  web.http.version.path: {{ .Values.issuerservice.endpoints.version.path | quote}}
  web.http.sts.port: {{ .Values.issuerservice.endpoints.sts.port | quote }}
  web.http.sts.path: {{ .Values.issuerservice.endpoints.sts.path | quote }}
  web.http.issuance.port: {{ .Values.issuerservice.endpoints.issuance.port | quote }}
  web.http.issuance.path: {{ .Values.issuerservice.endpoints.issuance.path | quote }}
  web.http.issueradmin.port: {{ .Values.issuerservice.endpoints.issueradmin.port | quote }}
  web.http.issueradmin.path: {{ .Values.issuerservice.endpoints.issueradmin.path | quote }}
  web.http.identity.port: {{ .Values.issuerservice.endpoints.identity.port | quote }}
  web.http.identity.path: {{ .Values.issuerservice.endpoints.identity.path | quote }}
  web.http.did.port: {{ .Values.issuerservice.endpoints.did.port | quote}}
  web.http.did.path: {{ .Values.issuerservice.endpoints.did.path | quote}}


  ###########
  ## VAULT ##
  ###########
  edc.vault.hashicorp.url: {{ tpl .Values.vault.hashicorp.url . | quote }}
  edc.vault.hashicorp.token: {{ .Values.vault.hashicorp.token | required ".Values.vault.hashicorp.token is required" | quote }}
  edc.vault.hashicorp.timeout.seconds: {{ .Values.vault.hashicorp.timeout | quote }}
  edc.vault.hashicorp.health.check.enabled: {{ .Values.vault.hashicorp.healthCheck.enabled | quote }}
  edc.vault.hashicorp.health.check.standby.ok: {{ .Values.vault.hashicorp.healthCheck.standbyOk | quote }}
  edc.vault.hashicorp.api.secret.path: {{ .Values.vault.hashicorp.paths.secret | quote }}
  edc.vault.hashicorp.api.health.check.path: {{ .Values.vault.hashicorp.paths.health | quote }}

  #################
  ## APPLICATION ##
  #################
  edc.issuer.statuslist.signing.key.alias: {{ .Values.statuslist.signing_key.alias | required ".Values.statuslist.signing.key.alias is required" | quote }}
  edc.iam.did.web.use.https: {{ .Values.issuerservice.didweb.https | quote }}
  edc.iam.accesstoken.jti.validation:  {{ .Values.issuerservice.jtivalidation | quote}}