#################################################################################
  #  Copyright (c) 2025 Cofinity-X
  #  Copyright (c) 2025 Contributors to the Eclipse Foundation
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0.
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #################################################################################


---

# this configmap contains all application configuration that is required by the identityhub runtime.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "identityhub-config"
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "identityhub.labels" . | nindent 4 }}
data:
  #######
  # API #
  #######

  web.http.port: {{ .Values.identityhub.endpoints.default.port | quote }}
  web.http.path: {{ .Values.identityhub.endpoints.default.path | quote }}
  web.http.identity.port: {{ .Values.identityhub.endpoints.identity.port | quote }}
  web.http.identity.path: {{ .Values.identityhub.endpoints.identity.path | quote }}
  web.http.identity.auth.alias: {{ .Values.identityhub.endpoints.identity.authKeyAlias | required ".Values.identityhub.endpoints.identity.authKeyAlias is required" | quote }}
  web.http.presentation.port: {{ .Values.identityhub.endpoints.presentation.port | quote }}
  web.http.presentation.path: {{ .Values.identityhub.endpoints.presentation.path | quote }}
  web.http.did.port: {{ .Values.identityhub.endpoints.did.port | quote }}
  web.http.did.path: {{ .Values.identityhub.endpoints.did.path | quote }}
  web.http.accounts.port: {{ .Values.identityhub.endpoints.accounts.port | quote}}
  web.http.accounts.path: {{ .Values.identityhub.endpoints.accounts.path | quote}}
  web.http.version.port: {{ .Values.identityhub.endpoints.version.port | quote}}
  web.http.version.path: {{ .Values.identityhub.endpoints.version.path | quote}}
  web.http.sts.port: {{ .Values.identityhub.endpoints.sts.port | quote}}
  web.http.sts.path: {{ .Values.identityhub.endpoints.sts.path | quote}}